spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/download?useUnicode=true&characterEncoding=utf-8
    username: root
    password:


logging:
  level:
    root: warn
    com.hogwarts.springboot: info
  file: log/blog-pro.log

server:
  port: 8081
