spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/download?useUnicode=true&characterEncoding=utf-8
    username: root
    password: jiayi071528

logging:
  level:
    root: info
    com.hogwarts.springboot: debug
  file: log/blog-dev.log